version: 2.1

jobs:
  build:
    docker:
      - image: 'openjdk:13-alpine'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud